on: push

jobs:
    release:
        uses: ./.github/workflows/versioning.yml
        permissions:
            id-token: write
            contents: write
            issues: write
            deployments: write
    report:
        runs-on: ubuntu-latest
        needs: release
        steps:
            - run: |
                echo "## new version ${{ needs.release.outputs.app_version }}" >> $GITHUB_STEP_SUMMARY