on: push

jobs:
    release:
        uses: ./.github/workflows/versioning.yml
        permissions:
            id-token: write
            contents: write
            issues: write
            deployments: write
